export const rows = [
  {
    id: 1,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 2,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 3,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 4,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 5,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 6,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 7,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 8,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 9,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 10,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 11,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 12,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 13,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 14,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 15,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 16,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
  {
    id: 17,
    score: 10,
    username: "Snow",
    date: "28-07-2022",
    category: "deportes",
    dificulty: "facil",
  },
];
